### ISSUE TITLE
Wonky Sandbox Transitions

### ISSUE THREAD

**Issue by Xansta** [tsnrp/TSN-Command-Systems#11]
Sandbox issues 30Apr2022:
In Atlantis XI, the GM locked transitions so that rimward transitions put us on the coreward side of Atlantis XI. This happened until we fed the nebula monster. After that, our intended route was Atlantis XI to Atlantis XVI through the gate to Cerberus, Cerberus II to Cerberus III to Cerberus IV, through the gate to Promethean, then Promethean VI to Promethean XI. However, transitions along the way were wonky and we eventually had to adjust by having the sandbox restart us in Promethean VI. 

I don't have much more in the way of specifics. It looked like the Atlantis gate in Cerberus II was following us and it looked like one of the trailing transitions in Cerberus took us to Cerberus I.
If someone was streaming, you might check their feed

**Comment by XavierWise** [comment]
Looked into this - it would seem that a System variable was being incorrectly set when using Jump Gate transitions. This should now be fixed.
