### ISSUE TITLE
ALL Pirate fleets only spawn single Euphini Arrow class vessel

### ISSUE THREAD

**Issue by camylarde** [tsnrp/TSN-Command-Systems#3]
Skull Pirates spawn menu has several single ship deployments, and several fleet ones. 
The fleet options however do not spawn Skull pirates, but Euphini, which has its own menu in the spawn menu tree. 
I do miss several options for Skull pirates fleets, mainly 3-4 ship formations without and with fighter support. 
Lt. Raiden.

**Comment by astrolamb-gaming** [comment]
Probably related to https://github.com/tsnrp/MISS_TSN-Sandbox/issues/5

**Comment by astrolamb-gaming** [comment]
Confirmed related to previous comment. ALL pirate fleet menu buttons spawn only a sinlge Arrow class vessel, not a whole fleet.

**Comment by XavierWise** [comment]
Skull Pirates updates. Fleets now spawn.
