### ISSUE TITLE
Switch Side of existing objects doesn't always work

### ISSUE THREAD

**Issue by m-kostrzewa** [tsnrp/TSN-Command-Systems#9]
![image](https://user-images.githubusercontent.com/9220158/164990886-6bb3ba14-dd7c-4441-b240-5b9ca9300ae0.png)

Setting side of an object through the above menu doesn't always work

In particular, buttons 5-12 never work. Button 4 sometimes works.

This is because buttons 5-12 (and partially button 4) are overlapping with "Marine Rv" and "Engineer Rv" buttons underneath, which take precedence:
![image](https://user-images.githubusercontent.com/9220158/164990933-7d2d6b10-6999-404b-978d-87a68ed09226.png)

Even though buttons 4-12 may be pressed (and even are animated), the press is never registered.

---

Suggested fix:

Since Rv operations are available through POI menu, I think the 4 Rv buttons underneath the AI section should be removed entirely. (There are some "menu clearing" issues with those Rv buttons anyways).

**Comment by XavierWise** [comment]
The RV point in the AI commands automatically stops the selected ship and spawns and RV point.

**Comment by XavierWise** [comment]
RV points have been moved to a new location to stop overlap of the Switch Side menu. RV points have been kept for use by GMs wanting to spawn RV points on a specific ship

**Comment by m-kostrzewa** [comment]
@XavierWise there is a similar issue with a button "behind" blocking buttons "in-front" when reassigning ship AI. "Reassigning AI" button blocks a bunch of fleet letters.
